version: '3.9'

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '5432:5432' # デバッグ用

  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    volumes:
      - ./backend:/code
      - ./static:/static
    ports:
      - '8000:8000'
      # デバッグ用ポート
      - '8080:8080'
    command: sh -c "/usr/local/bin/entrypoint.sh"
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'

  nginx:
    container_name: web
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    volumes:
      - ./static:/static
    ports:
      - 80:80
    depends_on:
      - app

  # volta検証のためコメントアウト
  # front:
  #   container_name: front
  #   build:
  #     context: .
  #     dockerfile: containers/front/Dockerfile
  #   volumes:
  #     - ./frontend:/code
  #     - node_modules_volume:/frontend/node_modules
  #   command: sh -c "npm run dev"
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     - NEXT_PUBLIC_RESTAPI_URL=http://localhost/back

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sns,ses,sqs
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - DEBUG=1
    volumes:
      - localstack_data:/tmp/localstack/data
      - localstack_bin:/var/lib/localstack

  doc:
    image: swaggerapi/swagger-ui
    container_name: doc
    volumes:
      - ./doc/openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      API_URL: openapi.yml
    ports:
      - 9000:8080

volumes:
  db_data:
  static:
  localstack_data:
  localstack_bin:
  node_modules_volume:

networks:
  default:
    name: testnet
